<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Finding How The Data Is Distributed**

Estimated time needed: **30** minutes

In this lab, you will work with a cleaned dataset to perform Exploratory Data Analysis (EDA). You will examine the structure of the data, visualize key variables, and analyze trends related to developer experience, tools, job satisfaction, and other important aspects.

## Objectives

In this lab you will perform the following:

- Understand the structure of the dataset.

- Perform summary statistics and data visualization.

- Identify trends in developer experience, tools, job satisfaction, and other key variables.

### Install the required libraries

In [1]:
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install SciPy

Collecting pandas
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 131.5 MB/s eta 0:00:00
Downloading numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 155.9 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.3.4 pandas-2.3.3 tzdata-2025.2
Collecting matplotlib
  Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.60.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (112 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 85.0 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.1-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 86.5 MB/s eta 0:00:00
Downloading kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 37.1 MB/s eta 0:00:00
Downloading pillow-12.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 104.0 MB/s eta 0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.60.1 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.12/site-packages (from seaborn) (2.3.4)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.12/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.12/site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Collecting SciPy
  Downloading scipy-1.16.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /opt/conda/lib/python3.12/site-packages (from SciPy) (2.3.4)
Downloading scipy-1.16.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.7/35.7 MB 132.1 MB/s eta 0:00:0000:01
Installing collected packages: SciPy
Successfully installed SciPy-1.16.2

### Step 1: Import Libraries and Load Data

- Import the `pandas`, `matplotlib.pyplot`, and `seaborn` libraries.

- You will begin with loading the dataset. You can use the pyfetch method if working on JupyterLite. Otherwise, you can use pandas' read_csv() function directly on their local machines or cloud environments.

In [4]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Stack Overflow survey dataset
data_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv'
df = pd.read_csv(data_url)

# Display the first few rows of the dataset
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

### Step 2: Examine the Structure of the Data

- Display the column names, data types, and summary information to understand the data structure.

- Objective: Gain insights into the dataset's shape and available variables.

In [3]:
df.shape

(65437, 114)

In [5]:
df.dtypes

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...
JobSatPoints_11        float64
SurveyLength            object
SurveyEase              object
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

### Step 3: Handle Missing Data

- Identify missing values in the dataset.

- Impute or remove missing values as necessary to ensure data completeness.

In [6]:
df.isnull().sum()

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

In [9]:
df.dropna
print ("NaN's have been dropped")

NaN's have been dropped

In [22]:
df.isnull().sum()

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

### Step 4: Analyze Key Columns

- Examine key columns such as `Employment`, `JobSat` (Job Satisfaction), and `YearsCodePro` (Professional Coding Experience).

- **Instruction**: Calculate the value counts for each column to understand the distribution of responses.

In [13]:
print(df['Employment'].value_counts())
print(df['JobSat'].value_counts())
print(df['YearsCodePro'].value_counts())

Employment
Employed, full-time                                                                                                                                   39041
Independent contractor, freelancer, or self-employed                                                                                                   4846
Student, full-time                                                                                                                                     4709
Employed, full-time;Independent contractor, freelancer, or self-employed                                                                               3557
Not employed, but looking for work                                                                                                                     2341
                                                                                                                                                      ...
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time        1
Student, full-time;Retired                                                                                                                                1
Employed, full-time;Not employed, but looking for work;Student, part-time                                                                                 1
Not employed, and not looking for work;Student, part-time;Employed, part-time                                                                             1
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired                                        1
Name: count, Length: 110, dtype: int64
JobSat
8.0     7509
7.0     6379
6.0     3751
9.0     3626
10.0    2251
5.0     1956
3.0     1165
4.0     1130
2.0      772
0.0      311
1.0      276
Name: count, dtype: int64
YearsCodePro
2                     4168
3                     4093
5                     3526
10                    3251
4                     3215
Less than 1 year      2856
6                     2843
1                     2639
8                     2549
7                     2517
12                    1777
15                    1635
20                    1549
9                     1493
11                    1312
13                    1127
14                    1082
25                     998
16                     946
18                     867
17                     814
30                     689
24                     632
19                     516
22                     492
23                     448
26                     426
27                     380
21                     380
28                     342
35                     285
29                     196
40                     194
32                     194
34                     169
38                     134
33                     132
36                     119
31                     106
37                     104
45                      56
42                      55
39                      54
41                      51
More than 50 years      50
44                      42
43                      37
46                      21
50                      14
48                      14
49                      11
47                      10
Name: count, dtype: int64

### Step 5: Visualize Job Satisfaction (Focus on JobSat)

- Create a pie chart or KDE plot to visualize the distribution of `JobSat`.

- Provide an interpretation of the plot, highlighting key trends in job satisfaction.

In [14]:
# piechart ofJobSat

# step1 Groupby

df_JobSat = df.groupby('JobSat', axis=0).sum()
print (type(df_JobSat.groupby('JobSat',axis=0)))
df_JobSat.head(2)

/tmp/ipykernel_299/2785939022.py:5: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  df_JobSat = df.groupby('JobSat', axis=0).sum()

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

/tmp/ipykernel_299/2785939022.py:6: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  print (type(df_JobSat.groupby('JobSat',axis=0)))

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly
JobSat,,,,,,,,,,,,,,,,,,,,,
0.0,8623276,I am a developer by professionI am a developer...,55-64 years old25-34 years old35-44 years old2...,"Employed, full-timeEmployed, full-timeEmployed...",RemoteRemoteRemoteRemoteRemoteIn-personRemoteR...,ApplesApplesApplesApplesApplesApplesApplesAppl...,I don’t code outside of workHobby;Contribute t...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)Ba...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,2496.0,5809.0,5437.0,4165.0,3584.0,2710.0,2384.0,Appropriate in lengthAppropriate in lengthAppr...,Neither easy nor difficultNeither easy nor dif...,13222820.0
1.0,7326638,I am a developer by professionI am a developer...,25-34 years old25-34 years old45-54 years old4...,"Employed, full-timeEmployed, full-timeEmployed...","RemoteHybrid (some remote, some in-person)Hybr...",ApplesApplesApplesApplesApplesApplesApplesAppl...,Hobby;Other (please specify):Professional deve...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)Ba...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Books;Written Tu...,...,1752.0,4919.0,4464.0,4292.0,3357.0,2186.0,1643.0,Appropriate in lengthAppropriate in lengthAppr...,EasyEasyNeither easy nor difficultNeither easy...,13597965.0

In [15]:
#Plot the data
df.JobSat['Total'].plot(kind='pie',
                        figsize = (5,6),
                        autopct ='%1.1f%%',
                        shortangle = 90,
                        shadow = True)
plt.title('Job Satisfaction Distribution')
plt.axis=('equal')
plt.legend (lables = df_JobSat.index,loc='upper left')
plt.show()

KeyError: 'Total'

### Step 6: Programming Languages Analysis

- Compare the frequency of programming languages in `LanguageHaveWorkedWith` and `LanguageWantToWorkWith`.
  
- Visualize the overlap or differences using a Venn diagram or a grouped bar chart.

In [ ]:
# Cross-tabulate RemoteWork by Employment type
Language_ct = pd.crosstab(df['LanguageHaveWorkedWith'], df['LanguageWantToWorkWith'])
print("Cross-tabulation of Lanaguge Have Worked With vs Language Want To Work With:")
print(Language-ct)

import pylab as plt


#Create a grouped bar chart

x=df[


x=np.arrange(5)
y1=

### Step 7: Analyze Remote Work Trends

- Visualize the distribution of RemoteWork by region using a grouped bar chart or heatmap.

In [16]:

# Group Remote Work by Region

df_Remotebyregion = df.groupby('RemoteWork','Region', axis=0).sum()
print (type(df_Remotebyregion.groupby('RemoteWork','Region',axis=0)))
df_Remotebyregion.head(2)


# Plot the heatmap with only these columns
plt.figure(figsize=(15, 10))
sns.heatmap(df_Remotebyregion, cbar=False, cmap='Blues', yticklabels=False)
plt.title('Heatmap of Remote Work Distribution by Region', fontsize=16)
plt.show()

TypeError: DataFrame.groupby() got multiple values for argument 'axis'

### Step 8: Correlation between Job Satisfaction and Experience

- Analyze the correlation between overall job satisfaction (`JobSat`) and `YearsCodePro`.
  
- Calculate the Pearson or Spearman correlation coefficient.

In [18]:
 #Step 8: Correlation Between Experience and Job Satisfaction ---

# Convert to numeric in case of string values
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')
df['JobSatPoints_1'] = pd.to_numeric(df['JobSatPoints_1'], errors='coerce')

pearson_coef, p_value = stats.pearsonr(
    df['YearsCodePro'].dropna(),
    df['JobSatPoints_1'].dropna()
)
print(f"Pearson Correlation Coefficient: {pearson_coef}")
print(f"P-value: {p_value}")

NameError: name 'stats' is not defined

### Step 9: Cross-tabulation Analysis (Employment vs. Education Level)

- Analyze the relationship between employment status (`Employment`) and education level (`EdLevel`).

- **Instruction**: Create a cross-tabulation using `pd.crosstab()` and visualize it with a stacked bar plot if possible.

In [17]:
# Cross-tabulate Employment by EdLevel
ed_employment_ct = pd.crosstab(df['Employment'], df['EdLevel'])
print("Cross-tabulation of Employment Type vs EducationLevel")
print(ed_employment_ct)




# Visualize Remote Work distribution by Employment Type with a stacked bar plot

# create the data

x=['Associate degree (A.A., A.S., etc.)', 'Bachelor’s degree (B.A., B.S., B.Eng., etc.)','Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
'Primary/elementary school', 'Professional degree (JD, MD, Ph.D, Ed.D, etc.)','Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)', 
'Some college/university study without earning a degree','Something else' ]

y1=np.array([Employment,Employed, full-time,Employed, full-time;Employed, part-time,Employed, full-time;Independent contractor, fre... ,Employed, full-time;
Independent contractor, fre.,Student, full-time;Student, part-time;Employed,...,Student, full-time;Student, part-time;Retired,Student, part-time,Student, part-time;Employed, 
part-time,Student, part-time;Employed, part-time,Student, part-time;Retired])

plt.bar(x,y1,color='r')
plt.bar(x,y2
plt.xlabel("EdLevel")
plt.ylabel("Employment")
plt.legend()
plt.title('Remote Work Preferences by Employment Type')
plt.show()

Cross-tabulation of Employment Type vs EducationLevel
EdLevel                                             Associate degree (A.A., A.S., etc.)  \
Employment
Employed, full-time                                                                1059
Employed, full-time;Employed, part-time                                               9
Employed, full-time;Independent contractor, fre...                                  104
Employed, full-time;Independent contractor, fre...                                   11
Employed, full-time;Independent contractor, fre...                                    0
...                                                                                 ...
Student, full-time;Student, part-time;Employed,...                                    0
Student, full-time;Student, part-time;Retired                                         0
Student, part-time                                                                   12
Student, part-time;Employed, part-time                                               24
Student, part-time;Retired                                                            0

EdLevel                                             Bachelor’s degree (B.A., B.S., B.Eng., etc.)  \
Employment
Employed, full-time                                                                        16806
Employed, full-time;Employed, part-time                                                       90
Employed, full-time;Independent contractor, fre...                                          1381
Employed, full-time;Independent contractor, fre...                                            79
Employed, full-time;Independent contractor, fre...                                             0
...                                                                                          ...
Student, full-time;Student, part-time;Employed,...                                             1
Student, full-time;Student, part-time;Retired                                                  0
Student, part-time                                                                           105
Student, part-time;Employed, part-time                                                       184
Student, part-time;Retired                                                                     0

EdLevel                                             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  \
Employment
Employed, full-time                                                                           11011
Employed, full-time;Employed, part-time                                                          61
Employed, full-time;Independent contractor, fre...                                              963
Employed, full-time;Independent contractor, fre...                                               45
Employed, full-time;Independent contractor, fre...                                                0
...                                                                                             ...
Student, full-time;Student, part-time;Employed,...                                                1
Student, full-time;Student, part-time;Retired                                                     0
Student, part-time                                                                               26
Student, part-time;Employed, part-time                                                           85
Student, part-time;Retired                                                                        2

EdLevel                                             Primary/elementary school  \
Employment
Employed, full-time                                                       160
Employed, full-time;Employed, part-time                                     1
Employed, full-time;Independent contractor, fre...                         25
Employed, full-time;Independent contractor, fre...                          1
Employed, full-time;Independent contractor, fre...                          0
...                                                                       ...
Student, full-time;Student, part-time;Employed,...                          1
Student, full-time;Student, part-time;Retired                               1
Student, part-time                                                         48
Student, part-time;Employed, part-time                                      4
Student, part-time;Retired                                                  0

EdLevel                                             Professional degree (JD, MD, Ph.D, Ed.D, etc.)  \
Employment
Employed, full-time                                                                           2073
Employed, full-time;Employed, part-time                                                          8
Employed, full-time;Independent contractor, fre...                                             159
Employed, full-time;Independent contractor, fre...                                              10
Employed, full-time;Independent contractor, fre...                                               1
...                                                                                            ...
Student, full-time;Student, part-time;Employed,...                                               0
Student, full-time;Student, part-time;Retired                                                    0
Student, part-time                                                                               5
Student, part-time;Employed, part-time                                                           5
Student, part-time;Retired                                                                       0

EdLevel                                             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)  \
Employment
Employed, full-time                                                                              1460
Employed, full-time;Employed, part-time                                                             9
Employed, full-time;Independent contractor, fre...                                                181
Employed, full-time;Independent contractor, fre...                                                  6
Employed, full-time;Independent contractor, fre...                                                  0
...                                                                                               ...
Student, full-time;Student, part-time;Employed,...                                                  0
Student, full-time;Student, part-time;Retired                                                       1
Student, part-time                                                                                140
Student, part-time;Employed, part-time                                                            100
Student, part-time;Retired                                                                          0

EdLevel                                             Some college/university study without earning a degree  \
Employment
Employed, full-time                                                                              3579
Employed, full-time;Employed, part-time                                                            15
Employed, full-time;Independent contractor, fre...                                                492
Employed, full-time;Independent contractor, fre...                                                 14
Employed, full-time;Independent contractor, fre...                                                  0
...                                                                                               ...
Student, full-time;Student, part-time;Employed,...                                                  4
Student, full-time;Student, part-time;Retired                                                       0
Student, part-time                                                                                 75
Student, part-time;Employed, part-time                                                            103
Student, part-time;Retired                                                                          1

EdLevel                                             Something else
Employment
Employed, full-time                                            377
Employed, full-time;Employed, part-time                          3
Employed, full-time;Independent contractor, fre...              41
Employed, full-time;Independent contractor, fre...               2
Employed, full-time;Independent contractor, fre...               0
...                                                            ...
Student, full-time;Student, part-time;Employed,...               0
Student, full-time;Student, part-time;Retired                    0
Student, part-time                                              17
Student, part-time;Employed, part-time                          14
Student, part-time;Retired                                       1

[106 rows x 8 columns]

### Step 10: Export Cleaned Data

- Save the cleaned dataset to a new CSV file for further use or sharing.

In [ ]:
## Write your code here

### Summary:

In this lab, you practiced key skills in exploratory data analysis, including:

- Examining the structure and content of the Stack Overflow survey dataset to understand its variables and data types.

- Identifying and addressing missing data to ensure the dataset's quality and completeness.

- Summarizing and visualizing key variables such as job satisfaction, programming languages, and remote work trends.

- Analyzing relationships in the data using techniques like:
    - Comparing programming languages respondents have worked with versus those they want to work with.
      
    - Exploring remote work preferences by region.

- Investigating correlations between professional coding experience and job satisfaction.

- Performing cross-tabulations to analyze relationships between employment status and education levels.

## Authors:
Ayushi Jain

### Other Contributors:
Rav Ahuja
Lakshmi Holla
Malika

Copyright © IBM Corporation. All rights reserved.